version: "3.8"

x-lsio-vars: &lsio_vars
  PUID: 911
  PGID: 911
  TZ: America/New_York
  UMASK: 022

networks:
  web:
    name: web
    external: true
  db:
    name: db
    external: true

services:
  bazarr:
    container_name: bazarr
    environment:
      <<: *lsio_vars
    hostname: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /data/bazarr:/config
      - /mnt/media/media:/mnt/media/media
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  dashy:
    container_name: dashy
    environment:
      NODE_ENV: production
      UID: 911
      GID: 911
    hostname: dashy
    image: lissy93/dashy:latest
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /data/dashy/conf.yml:/app/public/conf.yml
      - /data/dashy/icons:/app/public/item-icons
    healthcheck:
      test: [ "CMD", "node", "/app/services/healthcheck" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      com.centurylinklabs.watchtower.enable: "true"

      #   hass:
      #     container_name: hass
      #     environment:
      #       TZ: America/New_York
      #     hostname: hass
      #     image: homeassistant/home-assistant:latest
      #     restart: unless-stopped
      #     networks:
      #       - web
      #     volumes:
      #       - /data/hass:/config

  lidarr:
    container_name: lidarr
    environment:
      <<: *lsio_vars
    hostname: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /data/lidarr:/config
      - /mnt/media:/mnt/media
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  nzbget:
    container_name: nzbget
    environment:
      <<: *lsio_vars
    hostname: nzbget
    image: lscr.io/linuxserver/nzbget:latest
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /data/nzbget:/config
      - /mnt/media/usenet:/mnt/media/usenet
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  prowlarr:
    container_name: prowlarr
    environment:
      <<: *lsio_vars
    hostname: prowlarr
    image: lscr.io/linuxserver/prowlarr:nightly
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /data/prowlarr:/config
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  radarr:
    container_name: radarr
    environment:
      <<: *lsio_vars
    hostname: radarr
    image: lscr.io/linuxserver/radarr:nightly
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /data/radarr:/config
      - /mnt/media:/mnt/media
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  radarr-anime:
    container_name: radarr-anime
    environment:
      <<: *lsio_vars
    hostname: radarr-anime
    image: lscr.io/linuxserver/radarr:nightly
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /data/radarr-anime:/config
      - /mnt/media:/mnt/media
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  readarr:
    container_name: readarr
    environment:
      <<: *lsio_vars
    hostname: readarr
    image: lscr.io/linuxserver/readarr:develop
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /data/readarr:/config
      - /mnt/media:/mnt/media
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  recyclarr:
    container_name: recyclarr
    environment:
      TZ: America/New_York
    hostname: recyclarr
    image: ghcr.io/recyclarr/recyclarr:edge
    init: true
    user: 911:911
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /data/recyclarr:/config
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  resilio:
    container_name: resilio
    environment:
      <<: *lsio_vars
    hostname: resilio
    image: lscr.io/linuxserver/resilio-sync:latest
    restart: unless-stopped
    networks:
      - web
    ports:
      - 8888:8888
      - 55555:55555
    volumes:
      - /data/resilio/config:/config
      - /mnt/media/resilio/downloads:/downloads
      - /mnt/media/resilio/sync:/sync

  sabnzbd:
    container_name: sabnzbd
    environment:
      <<: *lsio_vars
    hostname: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /data/sabnzbd:/config
      - /mnt/media/usenet:/mnt/media/usenet
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  searcharr:
    container_name: searcharr
    environment:
      <<: *lsio_vars
    hostname: searcharr
    image: toddrob/searcharr:latest
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /data/searcharr/data:/app/data
      - /data/searcharr/logs:/app/logs
      - /data/searcharr/settings.py:/app/settings.py
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  sonarr:
    container_name: sonarr
    environment:
      <<: *lsio_vars
    hostname: sonarr
    image: lscr.io/linuxserver/sonarr:develop
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /data/sonarr:/config
      - /mnt/media:/mnt/media
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  sonarr-anime:
    container_name: sonarr-anime
    environment:
      <<: *lsio_vars
    hostname: sonarr-anime
    image: lscr.io/linuxserver/sonarr:develop
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /data/sonarr-anime:/config
      - /mnt/media:/mnt/media
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  tautulli:
    container_name: tautulli
    environment:
      <<: *lsio_vars
    hostname: tautulli
    image: ghcr.io/tautulli/tautulli:latest
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/tautulli/config:/config
      - /data/plex/Library/Application Support/Plex Media Server/Logs:/plex-logs:ro
      - /mnt/media/media/tv:/mnt/media/media/tv
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  transmission:
    cap_add:
      - NET_ADMIN
    container_name: transmission
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      <<: *lsio_vars
      CREATE_TUN_DEVICE: true
      ENABLE_UFW: false
      GLOBAL_APPLY_PERMISSIONS: false
      HEALTH_CHECK_HOST: google.com
      LOCAL_NETWORK: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      OPENVPN_CONFIG: mullvad_us_nyc
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60 --mute-replay-warnings
      OPENVPN_PASSWORD: ${TRANSMISSION_VPN_PASS}
      OPENVPN_PROVIDER: custom
      OPENVPN_USERNAME: ${TRANSMISSION_VPN_USER}
      TRANSMISSION_DOWNLOAD_DIR: /mnt/media/torrents
      TRANSMISSION_DOWNLOAD_QUEUE_SIZE: 10
      TRANSMISSION_INCOMPLETE_DIR: /mnt/media/torrents/intermediate
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: true
      TRANSMISSION_WATCH_DIR: /mnt/media/torrents/watch
      TRANSMISSION_WATCH_DIR_ENABLED: true
      TRANSMISSION_WEB_UI: flood-for-transmission
      WEBPROXY_ENABLED: false
    hostname: transmission
    image: haugene/transmission-openvpn:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
    restart: unless-stopped
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    networks:
      - web
    volumes:
      - /data/transmission/data:/data
      - /data/transmission/mullvad:/etc/openvpn/custom
      - /mnt/media/torrents:/mnt/media/torrents
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  youtube-dl:
    container_name: youtube-dl
    hostname: youtube-dl
    image: nbr23/youtube-dl-server:yt-dlp
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /data/youtube-dl/data:/youtube-dl
      - /data/youtube-dl/config.yml:/app_config/config.yml:ro
    labels:
      com.centurylinklabs.watchtower.enable: "true"
