version: "3.8"

name: immich

x-common-vars: &common_vars
  PUID: 812
  PGID: 812
  TZ: America/New_York

x-db-vars: &db_vars
  DB_HOSTNAME: immich-db
  DB_PORT: 5432
  DB_DATABASE_NAME: immich
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}

x-redis-vars: &redis_vars
  REDIS_HOSTNAME: immich-redis

x-nvidia-vars: &nvidia_vars
  NVIDIA_DRIVER_CAPABILITIES: all
  NVIDIA_VISIBLE_DEVICES: 1

networks:
  immich:
    name: immich
  web:
    name: web
    external: true

volumes:
  immich-db-data:
  immich-ml-data:

services:
  immich-server:
    command: [ "start.sh", "immich" ]
    container_name: immich-server
    depends_on:
      - immich-redis
      - immich-db
    environment:
      <<: [ *common_vars, *db_vars, *redis_vars ]
      IMMICH_MEDIA_LOCATION: /mnt/media/upload
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    hostname: immich-server
    networks:
      - immich
      - web
    restart: always
    user: 812:812
    volumes:
      - /mnt/media/upload:/mnt/media/upload
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"

  immich-microservices:
    command: [ "start.sh", "microservices" ]
    container_name: immich-microservices
    depends_on:
      - immich-redis
      - immich-db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
    environment:
      <<: [ *common_vars, *db_vars, *redis_vars, *nvidia_vars ]
      IMMICH_MEDIA_LOCATION: /mnt/media/upload
    hostname: immich-microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    networks:
      - immich
    restart: always
    volumes:
      - /mnt/media/upload:/mnt/media/upload
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"

  immich-ml:
    container_name: immich-ml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
    environment:
      <<: [ *common_vars, *nvidia_vars ]
    hostname: immich-ml
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    networks:
      - immich
    restart: always
    volumes:
      - immich-ml-data:/cache
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"

  immich-redis:
    container_name: immich-redis
    hostname: immich-redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
    networks:
      - immich
    restart: always
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"

  immich-db:
    container_name: immich-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: immich
    hostname: immich-db
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    networks:
      - immich
    restart: always
    volumes:
      - immich-db-data:/var/lib/postgresql/data
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"
