version: "3.8"

name: immich

x-db-vars: &db_vars
  DB_HOSTNAME: immich-db
  DB_PORT: 5432
  DB_DATABASE_NAME: immich
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}

x-redis-vars: &redis_vars
  REDIS_HOSTNAME: immich-redis

x-typesense-vars: &typesense_vars
  TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
  TYPESENSE_HOST: immich-ts
  TYPESENSE_DATA_DIR: /data

networks:
  immich:
    name: immich
  web:
    name: web
    external: true

volumes:
  immich-db-data:
  immich-ml-data:
  immich-ts-data:

services:
  immich-server:
    command: [ "start.sh", "immich" ]
    container_name: immich-server
    depends_on:
      - immich-redis
      - immich-db
      - immich-ts
    environment:
      <<: [*db_vars, *redis_vars, *typesense_vars]
      IMMICH_MEDIA_LOCATION: /mnt/media/upload
      TZ: America/New_York
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    hostname: immich-server
    networks:
      - immich
      - web
    restart: always
    volumes:
      - /mnt/media/upload:/mnt/media/upload
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"

  immich-microservices:
    command: [ "start.sh", "microservices" ]
    container_name: immich-microservices
    depends_on:
      - immich-redis
      - immich-db
      - immich-ts
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - video
    environment:
      <<: [*db_vars, *redis_vars, *typesense_vars]
      IMMICH_MEDIA_LOCATION: /mnt/media/upload
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: 1
      TZ: America/New_York
    hostname: immich-microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    networks:
      - immich
    restart: always
    volumes:
      - /mnt/media/upload:/mnt/media/upload
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"

  immich-ml:
    container_name: immich-ml
    hostname: immich-ml
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    networks:
      - immich
    restart: always
    volumes:
      - immich-ml-data:/cache
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"

  immich-ts:
    container_name: immich-ts
    environment:
      <<: [*typesense_vars]
      GLOG_minloglevel: 1
    hostname: immich-ts
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    networks:
      - immich
    restart: always
    volumes:
      - immich-ts-data:/data
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"

  immich-redis:
    container_name: immich-redis
    hostname: immich-redis
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5
    networks:
      - immich
    restart: always
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"

  immich-db:
    container_name: immich-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: immich
    hostname: immich-db
    image: postgres:14-alpine@sha256:50d9be76e9a90da4c781554955e0ffc79d9d5c4226838e64b36aacc97cbc35ad
    networks:
      - immich
    restart: always
    volumes:
      - immich-db-data:/var/lib/postgresql/data
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"
