version: "3.8"

networks:
  web:
    name: web
    external: true

volumes:
  portainer_data:
    external: true

services:
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ee:latest
    restart: always
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"
