version: "3.8"

networks:
  db:
    name: db
    external: true
  web:
    name: web
    external: true

volumes:
  teamcity-data:
  teamcity-logs:
  teamcity-db:

services:
  teamcity:
    container_name: teamcity
    hostname: teamcity
    image: jetbrains/teamcity-server
    restart: unless-stopped
    networks:
      - db
      - web
    ports:
      - "8111:8111"
    volumes:
      - teamcity-data:/data/teamcity_server/datadir
      - teamcity-logs:/opt/teamcity/logs

  teamcity-db:
    container_name: teamcity-db
    environment:
      POSTGRES_USER: ${TEAMCITY_DB_USER}
      POSTGRES_PASSWORD: ${TEAMCITY_DB_PASSWORD}
      POSTGRES_DB: ${TEAMCITY_DB}
    hostname: teamcity-db
    image: postgres:14
    restart: unless-stopped
    networks:
      - db
      - web
    volumes:
      - teamcity-db:/var/lib/postgresql
