version: "3.8"

networks:
  web:
    name: web
    external: true
  db:
    name: db
    external: true

volumes:
  ghost-db:

services:
#  ghost:
#    container_name: ghost
#    environment:
#      database__client: mysql
#      database__connection__host: ghost-db
#      database__connection__user: ${GHOST_DB_USER}
#      database__connection__password: ${GHOST_DB_PASS}
#      database__connection__database: ${GHOST_DB_NAME}
#      mail__transport: SMTP
#      mail__options__service: Mailgun
#      mail__options__host: smtp.mailgun.org
#      mail__options__port: 587
#      mail__options__auth__user: ${MAILGUN_USER}
#      mail__options__auth__pass: ${MAILGUN_PASS}
#      url: http://192.168.90.34:2368
#      NODE_ENV: development
#    hostname: ghost
#    image: ghost:3-alpine
#    ports:
#      - "2368:2368"
#    restart: unless-stopped
#    networks:
#      - web
#    volumes:
#      - /data/ghost:/var/lib/ghost/content
#    labels:
#      com.centurylinklabs.watchtower.monitor-only: "true"
#
#  ghost-db:
#    container_name: ghost-db
#    environment:
#      MYSQL_ROOT_PASSWORD: ${GHOST_DB_ROOT_PASS}
#      MYSQL_DATABASE: ${GHOST_DB_NAME}
#      MYSQL_USER: ${GHOST_DB_USER}
#      MYSQL_PASSWORD: ${GHOST_DB_PASS}
#    hostname: ghost-db
#    image: mysql:5.7
#    restart: unless-stopped
#    networks:
#      - db
#    volumes:
#      - ghost-db:/var/lib/mysql
#    labels:
#      com.centurylinklabs.watchtower.monitor-only: "true"
#
  swag:
    cap_add:
      - NET_ADMIN
    container_name: swag
    environment:
      PUID: 911
      PGID: 911
      TZ: America/New_York
      URL: ${SWAG_URL}
      SUBDOMAINS: wildcard
      VALIDATION: dns
      DNSPLUGIN: digitalocean
      EMAIL: ${SWAG_EMAIL}
      DHLEVEL: 2048
      ONLY_SUBDOMAINS: false
      EXTRA_DOMAINS: ${SWAG_EXTRA_DOMAINS}
      STAGING: false
    hostname: swag
    image: lscr.io/linuxserver/swag:latest
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /data/swag:/config
    labels:
      com.centurylinklabs.watchtower.monitor-only: "true"
